pipeline {
    agent any
    stages {
        stage('Build Application') {
            steps {
                sh 'mvn -f java-tomcat-sample/pom.xml clean package'
		echo env.WORKSPACE
            }
            post {
                success {
                    echo "Now Archiving the Artifacts...."
                    archiveArtifacts artifacts: '**/*.war'
                   }
            }
	}
	stage('Deploy in Staging Environment'){

            steps{
                build job: 'Deploy Application to Staging Environment'
            }
         
        }
	stage('Deploy in Production Environment'){

            steps{

		timeout(time:5,unit:'DAYS'){

			input message: 'Approve PRODUCTION Deployement?'

		}
                build job: 'Deploy Application to Pro Environment'
            }
         
        }
    }
}
